dist: xenial

language: python
python:
  - 3.6
  - 3.7
  - 3.8
node_js: '8'

install:
  - pip install -U tox-travis
  - pip install coveralls

script:
  - tox -r

after_success:
  - coveralls

notifications:
  email: false
